#LeeesHomeSpawn Ver 1.2
blocksfromspawn: 3000
tpamessage: "&6[&18b&98t&6] You must be &c3000 &6blocks from spawn to use /tpa :("
homemessage: "&6[&18b&98t&6] You must be &c3000 &6blocks from spawn to use /home :("